### ISSUE TITLE
streaming_pull_future.cancel() hangs

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/python-pubsublite#95]
How to reproduce:

```sh
cd samples/snippets/
pip install -r requirements.txt
python subscriber_example.py $PROJECT_ID $REGION $ZONE_ID $SUBSCRIPTION_ID 60
```

The timeout exception is caught first, but calling `cancel()` on the future returned by the subscriber client next hangs:

```
Traceback (most recent call last):
  File "subscriber_example.py", line 74, in receive_messages
    streaming_pull_future.result(timeout=timeout)
  File "/Users/tianzi/.virtualenvs/py388/lib/python3.8/site-packages/google/cloud/pubsub_v1/futures.py", line 102, in result
    err = self.exception(timeout=timeout)
  File "/Users/tianzi/.virtualenvs/py388/lib/python3.8/site-packages/google/cloud/pubsub_v1/futures.py", line 122, in exception
    raise exceptions.TimeoutError("Timed out waiting for result.")
concurrent.futures._base.TimeoutError: Timed out waiting for result.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "subscriber_example.py", line 99, in <module>
    receive_messages(
  File "subscriber_example.py", line 76, in receive_messages
    streaming_pull_future.cancel()
  File "/Users/tianzi/.virtualenvs/py388/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/futures.py", line 62, in cancel
    return self._manager.close(await_msg_callbacks=await_msg_callbacks)
TypeError: close() got an unexpected keyword argument 'await_msg_callbacks'
```

**Comment by dpcollins-google** [comment]
This issue has been resolved by rolling back the update to the pubsub library
